ruby:
  config_file: ./ruby/.rubocop.yml

rubocop:
  version: 0.72.0

jshint:
  enabled: false

eslint:
  enabled: true
  config_file: ./javascript/.eslintrc.json

scss:
  config_file: ./scss/.scss-lint.yml
